# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Store-HTML
version:      0.301
version_from: lib/Email/Store/HTML.pm
installdirs:  site
requires:
    Email::Store:                  0
    HTML::FormatText::WithLinks:   0
    HTML::Scrubber:                0
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
